scalecube/scalecube

cluster/src/main/java/io/servicefabric/cluster/Cluster.java
cluster/src/main/java/io/servicefabric/cluster/ClusterMember.java
cluster/src/main/java/io/servicefabric/cluster/ClusterMembership.java
cluster/src/main/java/io/servicefabric/cluster/ICluster.java
cluster/src/main/java/io/servicefabric/cluster/IClusterMembership.java
examples/src/main/java/io/servicefabric/examples/transport/ClusterNodeB.java

1. add ICluster.isLocalMember(ClusterMember member) to validate if a given member is local member
2. improve the examples

add ICluster.isLocalMember(ClusterMember member) to validate if a given

---

benchmark/pom.xml
benchmark/src/main/java/cache/CacheReadBenchmark.java
benchmark/src/main/java/io/servicefabric/cluster/gossip/ProtostuffGossipBenchmark.java
benchmark/src/main/java/io/servicefabric/transport/protocol/ProtostuffMessageBenchmark.java
cluster/src/main/java/io/servicefabric/cluster/gossip/Gossip.java
cluster/src/main/java/io/servicefabric/cluster/gossip/GossipRequest.java
cluster/src/test/java/io/servicefabric/cluster/gossip/GossipProtocolFunctionTest.java
pom.xml
transport/src/main/java/io/servicefabric/transport/protocol/Message.java
transport/src/main/java/io/servicefabric/transport/protocol/MessageSchema.java

Here's new PR branched from ``benchmark/message_api`` with refactored tests and applied code review comments from PR#25.

benchmark/message api; refactored benchmarks

---

transport/src/main/java/io/servicefabric/transport/TransportHeaders.java
transport/src/main/java/io/servicefabric/transport/protocol/MessageSchema.java

if data class can't be resolved by name on intermediate node.

Issue #34 Fix MessageSchema to avoid data type lost

---

cluster/pom.xml
cluster/src/main/java/io/servicefabric/cluster/Cluster.java
cluster/src/main/java/io/servicefabric/cluster/ClusterMembership.java
cluster/src/main/java/io/servicefabric/cluster/ICluster.java
cluster/src/main/java/io/servicefabric/cluster/IManagedClusterMembership.java
cluster/src/test/java/io/servicefabric/cluster/ClusterMembershipBuilder.java
cluster/src/test/java/io/servicefabric/cluster/fdetector/FailureDetectorBuilder.java
cluster/src/test/java/io/servicefabric/cluster/gossip/GossipEmulationIT.java
examples/src/main/java/io/servicefabric/examples/ClusterBootstrapExamples.java
examples/src/main/java/io/servicefabric/examples/gossip/ClusterNodeA.java
examples/src/main/java/io/servicefabric/examples/gossip/ClusterNodeB.java
examples/src/main/java/io/servicefabric/examples/metadata/ClusterMetadata.java
examples/src/main/java/io/servicefabric/examples/transport/ClusterNodeA.java
examples/src/main/java/io/servicefabric/examples/transport/ClusterNodeB.java
pom.xml
transport/src/main/java/io/servicefabric/transport/ITransport.java
transport/src/main/java/io/servicefabric/transport/Transport.java
transport/src/test/java/io/servicefabric/transport/TransportTest.java

Motivation:
* There should not be blocking calls in Cluster API
Done:
* Make transport start async
* Make cluster start async

#28 Improve Cluster join API. Make join async.

---

services/src/main/java/io/scalecube/services/DispatchingFuture.java
services/src/main/java/io/scalecube/services/Microservices.java
services/src/main/java/io/scalecube/services/RemoteServiceInstance.java
services/src/main/java/io/scalecube/services/ResponseFuture.java
services/src/main/java/io/scalecube/services/ServiceDispatcher.java
services/src/main/java/io/scalecube/services/ServiceHeaders.java
services/src/main/java/io/scalecube/services/ServiceProxyFactory.java
services/src/test/java/io/scalecube/services/GreetingService.java
services/src/test/java/io/scalecube/services/GreetingServiceImpl.java
services/src/test/java/io/scalecube/services/ServicesIT.java
transport/src/main/java/io/scalecube/transport/Transport.java
transport/src/test/java/io/scalecube/transport/TransportTest.java

transport on backpreasure when sending 5000 messages at once
once adding onBackpressureBuffer on listen method it does not fails

backpreasure issue #93

---

services/src/main/java/io/scalecube/services/LocalServiceInstance.java
services/src/main/java/io/scalecube/services/Microservices.java
services/src/main/java/io/scalecube/services/RemoteServiceInstance.java
services/src/main/java/io/scalecube/services/ServiceInfo.java
services/src/main/java/io/scalecube/services/ServiceInstance.java
services/src/main/java/io/scalecube/services/ServiceRegistry.java
services/src/main/java/io/scalecube/services/ServiceRegistryImpl.java
services/src/main/java/io/scalecube/services/ServicesConfig.java
services/src/main/java/io/scalecube/services/annotations/AnnotationServiceProcessor.java
services/src/main/java/io/scalecube/services/annotations/ServiceProcessor.java
services/src/test/java/io/scalecube/services/ServicesIT.java
services/src/test/java/io/scalecube/services/a/b/testing/CanaryService.java
services/src/test/java/io/scalecube/services/a/b/testing/CanaryTestingRouter.java
services/src/test/java/io/scalecube/services/a/b/testing/GreetingServiceImplA.java
services/src/test/java/io/scalecube/services/a/b/testing/GreetingServiceImplB.java
services/src/test/java/io/scalecube/services/a/b/testing/RandomCollection.java
services/src/test/java/io/scalecube/services/a/b/testing/ServiceInfoTests.java
services/src/test/java/io/scalecube/services/a/b/testing/ServiceTagsExample.java

support service tag alternative implementation not using json parser and not using Tag model but Map<String,String>

Support service tags

---

transport/src/main/java/io/scalecube/transport/Transport.java
transport/src/test/java/io/scalecube/transport/TransportTest.java

Fixing following issue https://github.com/scalecube/scalecube/issues/92

Issue#92 Starting many nodes at once throw exception address already in use

---

cluster/src/main/java/io/scalecube/cluster/ClusterMath.java
cluster/src/main/java/io/scalecube/cluster/gossip/GossipConfig.java
cluster/src/main/java/io/scalecube/cluster/gossip/GossipProtocol.java
cluster/src/main/java/io/scalecube/cluster/membership/MembershipProtocol.java
cluster/src/main/java/io/scalecube/cluster/membership/MembershipRecord.java
cluster/src/test/java/io/scalecube/cluster/ClusterTest.java
cluster/src/test/java/io/scalecube/cluster/fdetector/FailureDetectorTest.java
cluster/src/test/java/io/scalecube/cluster/gossip/GossipProtocolTest.java
cluster/src/test/java/io/scalecube/cluster/gossip/GossipRequestTest.java
cluster/src/test/java/io/scalecube/cluster/membership/MembershipProtocolTest.java
cluster/src/test/java/io/scalecube/cluster/membership/MembershipRecordTest.java
testlib/src/main/java/io/scalecube/testlib/BaseTest.java
transport/src/test/java/io/scalecube/transport/AddressTest.java

See commit messages for changes.

Stabilize membership protocol

---

.travis.yml
pom.xml

add token for yaml

---

services/src/main/java/io/scalecube/services/ServiceProxyFactory.java

Signed-off-by: nuwan sanjeewa abeysiriwardana <nuwan077@gmail.com>

fixed proxy api resolve issue when it call inside the service

---

services/src/main/java/io/scalecube/services/LocalServiceInstance.java
services/src/main/java/io/scalecube/services/ServiceDispatcher.java
services/src/main/java/io/scalecube/services/ServiceHeaders.java
services/src/main/java/io/scalecube/services/ServiceProxyFactory.java
services/src/main/java/io/scalecube/services/routing/RouterFactory.java
services/src/test/java/io/scalecube/services/DispatchingFutureTest.java
services/src/test/java/io/scalecube/services/DummyRouter.java
services/src/test/java/io/scalecube/services/GreetingServiceImpl.java
services/src/test/java/io/scalecube/services/RoutersTest.java
services/src/test/java/io/scalecube/services/ServiceCallTest.java
services/src/test/java/io/scalecube/services/ServiceConfigTest.java
services/src/test/java/io/scalecube/services/ServiceDefinitionTest.java
services/src/test/java/io/scalecube/services/ServiceHeadersTest.java
services/src/test/java/io/scalecube/services/ServiceInstanceTest.java
services/src/test/java/io/scalecube/services/ServiceReferenceTest.java
services/src/test/java/io/scalecube/services/ServiceTest.java

add example test working with cluster configuration for advanced settings.
Microservices node = Microservices.builder().clusterConfig(
ClusterConfig.builder()
.transportConfig(TransportConfig.builder()
.port(3000)
.portAutoIncrement(false)
.build())) // cluster config
.build(); // node

Reduce Tech dept - Code coverage and quality 

---

services/src/test/java/io/scalecube/services/DispatchingFutureTest.java

add more cases completing Exceptionally

check error cases complete Exceptionally or with exception

---

services/src/main/java/io/scalecube/services/Microservices.java
services/src/test/java/io/scalecube/services/MicroservicesTest.java
services/src/test/java/io/scalecube/services/ServiceDispatcherTest.java
services/src/test/java/io/scalecube/services/ServiceInstanceTest.java

add more tests for microservices and dispatcher and service instance

---

services/src/test/java/io/scalecube/services/MicroservicesTest.java
services/src/test/java/io/scalecube/services/ServiceDispatcherTest.java

add tests for unregister service

---

CHANGES.md

Add member host/port overrides on member config in change log
add  Shout-out:
- Mike Barker on first contribution.

update change log

---

transport/src/main/java/io/scalecube/transport/Addressing.java
transport/src/main/java/io/scalecube/transport/Transport.java
transport/src/main/java/io/scalecube/transport/TransportImpl.java
transport/src/test/java/io/scalecube/transport/TransportTest.java

Fix to issue https://github.com/scalecube/scalecube/issues/207

Fixing issue #207 with inifinite loop at transport bind

---

services/src/main/java/io/scalecube/services/ServiceRegistryImpl.java
services/src/main/java/io/scalecube/services/ThreadFactory.java

Create daemon thread for service-registry-discovery

Fix for #219

---

travis-settings.xml

Fix travis settings.xml

---

.travis.yml

* Make DefaultEventStream, added tests; refactored (#216)
* Added tests, added DefaultEventStream
* Fix for #219 (#220)
Create daemon thread for service-registry-discovery
* Enable continues delivery (#215)
* add travis-settings.xml
* Update travis-settings.xml
fix server id
* Update .travis.yml
deploy maven artifacts on each commit to the master
* Deployment split:
+++ on develop branch: mvn deploy
+++ on master branch: mvn release
* Fix travis settings.xml (#222)
Fix server ID
* Enable continues delivery (#224)
* add travis-settings.xml
* Update travis-settings.xml
fix server id
* Update .travis.yml
deploy maven artifacts on each commit to the master
* Deployment split:
+++ on develop branch: mvn deploy
+++ on master branch: mvn release
* Enable CI (#221)
* Make DefaultEventStream, …

Enable CI (#227)

---

services/src/main/java/io/scalecube/services/Microservices.java
services/src/main/java/io/scalecube/services/ServiceCall.java
services/src/main/java/io/scalecube/services/ServiceHeaders.java
services/src/main/java/io/scalecube/services/ServiceProxyFactory.java
services/src/main/java/io/scalecube/services/ServiceReference.java
services/src/main/java/io/scalecube/services/ThreadFactory.java

This PR is attempt to fix this failing job -- https://api.travis-ci.org/v3/job/353733626/log.txt

Added missed javadocs

---

CHANGES.md
services/src/main/java/io/scalecube/services/RemoteServiceInstance.java
services/src/test/java/io/scalecube/services/DispatchingFutureTest.java
services/src/test/java/io/scalecube/services/Generator.java
services/src/test/java/io/scalecube/services/GeneratorService.java
services/src/test/java/io/scalecube/services/GracefulShutdownTest.java
services/src/test/java/io/scalecube/services/ServiceCallTest.java
services/src/test/java/io/scalecube/services/ServiceTest.java
services/src/test/java/io/scalecube/services/SimpleGenerator.java

fix for #291 #289 
thanks you @rasentry for opening the issue and offering solution.
thanks you @segabriel for providing a reproduction code.

fix duplicate responses issue #291 #289
